### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by hrj** [commonsearch/cosr-participation#14]
I hope this is an acceptable place to share some thoughts. I don't want to use Slack (because it's yet another proprietary non-federated silo).
- Please use a federated and open protocol for communication, such as XMPP or Matrix. (You seem to have an email channel but it's protected behind a cloudflare javascripted page, which doesn't want to reveal its secrets to me for some reason).
- Please provide a non-JS frontend eventually. DDG provides `https://duckduckgo.com/html` and its very useful.

**Comment by hrj** [comment]
Oh, I had one more thought:
- How do you combat gamification of your data? If your page ranking is transparent, it is easier for spammers, SEO hackers, etc to game the rankings. I mean, they reverse engineer and game the opaque rankings.

I didn't see that addressed in the FAQ.

**Comment by sylvinus** [comment]
Hi @hrj!

Thanks for your feedbacks! https://discuss.commonsearch.org/ is another great place to discuss such things.

We had an IRC channel open, but even if the protocol is open, IRC feels like a very closed place to new people. I'm (obviously) not a fan of proprietary things either but I'm also a pragmatist and Slack is just the best tool for the job right now. That said they do have an IRC gateway, I'll investigate that.

Our frontend should work perfectly with JS disabled, what made you think otherwise?

Your question about rankings is actually the 3rd in the FAQ:
https://about.commonsearch.org/faq

As you said people are already gaming opaque rankings, so we think a large community working on open rankings and manual reporting will be stronger than the spammers. We already have very good open source tools and community initiatives to fight email spam for instance so it's not impossible, though it will undoubtedly be difficult.

Let me know if you have further questions and we'd love to have you as a contributor!

**Comment by hrj** [comment]
Thanks for answering my questions.

Looks like I hadn't paid attention; you seem to have most things covered.

Do let me know if you figure out the IRC end. I just want to lurk around for the moment. When it's ready, apart from using it I would be happy to add a link to it in [gngr](https://github.com/uprootlabs/gngr).

Edit: @sylvinus Completely off-topic, but oh, you are the founder of jamendo! I have discovered some really cool music through it! Thanks!

**Comment by sylvinus** [comment]
I'm glad you were a jamendo fan @hrj ;-)

I'm going to add IRC instructions to the website, if you want to test just register on slack.commonsearch.org first and then follow the instructions here: https://get.slack.help/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

gngr looks great! Just tested it on our UI demo, things seem to mostly work but there is an issue with scrolling on result pages (at least on Mac OS).
